# | =================================================== |
# | This plugin is a fork from:                         |
# |   https://www.spigotmc.org/resources/23696/         |
# |   https://github.com/LMBishop/Quests/               |
# |                                                     |
# | Modifications permitted via MIT License             |
# | =================================================== |

# Categories are a way of grouping up quests.
# When a player uses /quests, a menu of categories will be presented to them.
# When a player clicks on a category, a list of quests under that category will show.
# If categories are disabled, all quests will be shown under one big GUI.
# Players can access specific categories by command using /quests c [category].
# If a quest does not have a category, it will not be shown.

categories:
  examples:
    display:
      name: "&cExample Quests"
      lore:
        - "&7Exampe quests bundled with the plugin."
      type: "WATER_BUCKET"
  permissionexample:
    display:
      name: "&cPermission Example"
      lore:
        - "&7This category requires a permission to open."
      type: "LAVA_BUCKET"
    # This category needs the permission "quests.category.permissionexample"
    # The permission for other categories is: "quests.category.<id>".
    permission-required: true

gui:
  back-button:
    name: "&cReturn"
    lore:
      - "&7Return to the category menu."
    type: "ARROW"
  page-prev:
    name: "&7Previous Page"
    lore:
      - "&7Go to page &c{prevpage}&7."
    type: "FEATHER"
  page-next:
    name: "&7Next Page"
    lore:
      - "&7Go to page &c{nextpage}&7."
    type: "FEATHER"
  page-desc:
    name: "&7Page &c{page}"
    lore:
      - "&7Currently viewing page &c{page}&7."
    type: "PAPER"
  quest-locked-display:
    name: "&c&lQuest Locked"
    lore:
      - "&7Complete &c{requirements}"
      - "&7to unlock &a{quest}&7."
    type: "RED_STAINED_GLASS_PANE"
  quest-permission-display:
    name: "&6&lNo Permission"
    lore:
      - "&7You do not have permission for this quest."
    type: "BROWN_STAINED_GLASS_PANE"
  quest-cooldown-display:
    name: "&e&lQuest on Cooldown"
    lore:
      - "&7You have recently completed &a{quest}&7."
      - "&7It will unlock in &e{time}&7."
    type: "ORANGE_STAINED_GLASS_PANE"
  quest-completed-display:
    name: "&a&lQuest Complete"
    lore:
      - "&7You have completed &a{quest}&7."
    type: "GREEN_STAINED_GLASS_PANE"
  quest-cancel-yes:
    name: "&a&lConfirm Cancellation"
    lore:
      - "&7Cancel &a{quest} &7and lose all progress?"
    type: "GREEN_STAINED_GLASS_PANE"
  quest-cancel-no:
    name: "&c&lKeep Questing"
    lore:
      - "&7Keep &a{quest} &7active."
      - "&7Return to the quest menu."
    type: "RED_STAINED_GLASS_PANE"
  quest-cancel-background:
    type: "GRAY_STAINED_GLASS_PANE"

options:
  # If categories are disabled, quests will be put into one big gui.
  categories-enabled: false
  # If true, the gui size will automatically change based on the amount of quests inside it.
  trim-gui-size: true
  # Enable/disable titles
  titles-enabled: true
  # Players cannot start any more quests than this at a single time
  quest-started-limit: 4
  # Hide locked quests, quests on cooldown and completed (but not repeatable) quests
  gui-hide-locked: false
  # Allow players to cancel a quest
  allow-quest-cancel: true
  # Titles for the GUIs
  guinames:
    quests-category: "Quest Categories"
    quests-menu: "Quests"
    quest-cancel: "Cancel Quest"
  # Show when quests register in console - will only show if verbose-logging-level=2. Disable if you want less console spam at startup.
  show-quest-registrations: true
  # Hide quests which a player cannot start due to permissions.
  gui-hide-quests-nopermission: false
  # Hide categories which a player cannot open due to permissions.
  gui-hide-categories-nopermission: false
  # Make it so players do not have to start quest themselves
  quest-autostart: false
  # How much quests should log, 0 = errors only, 1 = warnings, 2 = info, 3 = debug
  verbose-logging-level: 1
  performance-tweaking: # The following are measured in server ticks, multiply SECONDS by 20 to get the number of ticks.
    quest-completer-poll-interval: 100 # how frequently Quests should check if quests have been completed (def=100 - 5 seconds) - increase this value if you are struggling with performance
    quest-autosave-interval: 12000 # how frequently online players data will be autosaved (def=12000 - 10 minutes)

# Configure titles
titles:
  quest-start:
    title: "&cQuest Started"
    subtitle: "&7{quest}"
  quest-complete:
    title: "&cQuest Complete"
    subtitle: "&7{quest}"

# Configure messages
messages:
  time-format: "{hours}h {minutes}m"
  quest-start: "&7Quest &c{quest} &7started!"
  quest-complete: "&7Quest &c{quest} &7completed!"
  quest-cancel: "&7Quest &c{quest} &7cancelled!"
  quest-start-limit: "&7Players are limited to &c{limit} &7started quests at a time."
  quest-start-disabled: "&7You cannot repeat this quest."
  quest-start-locked: "&7You have not unlocked this quest yet."
  quest-start-cooldown: "&7You have recently completed this quest. You have to wait &c{time} &7until you are able to restart it."
  quest-start-started: "&7You have already started this quest."
  quest-start-permission: "&7You do not have permission to start this quest."
  quest-category-permission: "&7You do not have permission to view this category."
  quest-category-quest-permission: "&7You do not have permission to start this quest since it is in a category you do not have permission to view."
  quest-cancel-notstarted: "&7You have not started this quest."
  command-sub-doesntexist: "&7The specified subcommand '&c{sub}' &7does not exist."
  command-quest-start-doesntexist: "&7The specified quest '&c{quest}&7' does not exist."
  command-category-open-disabled: "&7Categories are disabled."
  command-category-open-doesntexist: "&7The specified category '&c{category}&7' does not exist."
  command-quest-admin-playernotfound: "&7Player '&c{player}&7' could not be found."
  command-quest-openquests-admin-success: "&7Opened Quest GUI for player &c{player}&7."
  command-quest-opencategory-admin-success: "&7Opened category &c{category} &7for player &c{player}&7."
  command-taskview-admin-fail: "&7Task type '&c{task}&7' does not exist."
  command-quest-admin-loaddata: "&7Quest data for '&c{player}&7' is being loaded."
  command-quest-admin-nodata: "&7No data could be found for player &c{player}&7."
  command-quest-admin-fullreset: "&7Data for player &c{player}&7 has been fully reset."
  command-quest-admin-start-faillocked: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have not yet unlocked it."
  command-quest-admin-start-failcooldown: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is still on cooldown for them."
  command-quest-admin-start-failcomplete: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have already completed it."
  command-quest-admin-start-faillimit: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have reached their quest start limit."
  command-quest-admin-start-failstarted: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is already started."
  command-quest-admin-start-failpermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission."
  command-quest-admin-start-failcategorypermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission for the category which the quest is in."
  command-quest-admin-start-failother: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7."
  command-quest-admin-start-success: "&7Quest &c{quest} &7started for player &c{player}&7."
  command-quest-admin-category-permission: "&7Category &c{category} &7 could not be opened for player &c{player}&7. They do not have permission to view it."
  command-quest-admin-complete-success: "&7Quest &c{quest} &7completed for player &c{player}&7."
  command-quest-admin-reset-success: "&7Successfully reset quest '&c{quest}&7' for player &c{player}&7."
